# Generated by Django 6.0.1 on 2026-04-20 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Nome/Razao Social')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('servico', models.CharField(choices=[('geral', 'Geral / Civil'), ('eletrica', 'Eletrica'), ('solar', 'Energia Solar'), ('climatizacao', 'Climatizacao'), ('automacao', 'Automacao')], default='geral', max_length=50)),
                ('origem', models.CharField(choices=[('site', 'Site / Google'), ('instagram', 'Instagram'), ('indicacao', 'Indicacao'), ('passante', 'Passante'), ('ativo', 'Prospeccao ativa')], default='site', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estagio', models.CharField(choices=[('contactar', 'A contactar'), ('enviar', 'Enviar proposta'), ('negociacao', 'Em negociacao'), ('credito', 'Analise de credito'), ('followup', 'Follow up'), ('aprovada', 'Venda aprovada'), ('perdido', 'Perdido')], default='contactar', max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('nota', 'Nota interna'), ('ligacao', 'Ligacao'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita tecnica'), ('email', 'E-mail'), ('movimentacao', 'Movimentacao')], default='nota', max_length=30)),
                ('nota', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='crm.lead')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
