# Generated by Django 6.0.1 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pipelinestage_alter_lead_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='servico',
            field=models.CharField(choices=[('solar', 'Energia Solar'), ('climatizacao', 'Climatizacao')], default='solar', max_length=50),
        ),
    ]
