# Generated by Django 6.0.1 on 2026-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_campaign_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='empresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='servico_interesse',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='lead',
            name='servico',
            field=models.CharField(choices=[('spda', 'Laudo de SPDA'), ('eletrico', 'Laudo de Instalacoes Eletricas'), ('ambos', 'SPDA e Instalacoes Eletricas'), ('orcamento', 'Solicitar Orcamento'), ('solar', 'Energia Solar'), ('climatizacao', 'Climatizacao')], default='solar', max_length=50),
        ),
    ]
